name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Replace with the version you are using

      - name: Configure SSH Key (Optional)
        if: env.SSH_PUBLIC_KEY != ''
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/new_azure_key.pub

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan

      - name: Set Terraform Output
        run: echo "terraform_output=$(terraform output -json)" >> $GITHUB_ENV

      - name: Post-Apply Actions
        run: |
          echo "Terraform deployment complete."
          echo "Outputs: ${{ env.terraform_output }}"
        env:
          terraform_output: ${{ env.terraform_output }}
